#!/usr/bin/env bash
# Rebuild/relaunch Engine or Manager on save (not HMR). Ctrl+C stops watch and the app.
# ./dev-watch.sh engine                    — dev Engine (stops the installed Engine first)
# ./dev-watch.sh manager                   — Manager with the pinned imago git rev
# ./dev-watch.sh manager --local-imago     — Manager against ../imago, also watches its crates
# Extra flags: --build (cargo build once, no watch/run), --dry-run (print, do not execute).
set -euo pipefail
cd "$(dirname "$0")"

usage() { echo "Usage: $0 engine|manager [--local-imago] [--build] [--dry-run]" >&2; exit 2; }
mode="${1:-}"; [[ $# -gt 0 ]] && shift
local_imago=0 build=0 dry=0
for arg in "$@"; do
    case "$arg" in
        --local-imago) local_imago=1 ;;
        --build) build=1 ;;
        --dry-run) dry=1 ;;
        *) usage ;;
    esac
done

# The installed Engine and the dev Engine share one data dir/singleton: ask the
# installed one (any mundus-engine.exe outside this target dir) to exit first.
stop_installed_engine() {
    TARGET_DIR="${CARGO_TARGET_DIR:-$(pwd -W)/target}" \
    powershell.exe -NoProfile -Command '
        $dev = [IO.Path]::GetFullPath($env:TARGET_DIR).TrimEnd("\") + "\"
        $outside = { Get-Process mundus-engine -ErrorAction SilentlyContinue | Where-Object { $_.Path -and -not $_.Path.StartsWith($dev, "OrdinalIgnoreCase") } }
        $exes = @(& $outside | ForEach-Object Path | Sort-Object -Unique)
        foreach ($exe in $exes) { Write-Host "stopping installed Engine: $exe"; & $exe --shutdown | Out-Null }
        if ($exes) {
            Start-Sleep -Seconds 3
            if (& $outside) { Write-Warning "installed Engine still running; the dev Engine may conflict with it" }
        }' || echo "warning: could not check for an installed Engine" >&2
}

case "$mode" in
    engine)
        [[ $local_imago -eq 0 ]] || usage
        watch=(--watch runtime/src --watch runtime/Cargo.toml --watch runtime/crates)
        cmd="cargo run -p engine --bin mundus-engine"
        [[ $build -eq 0 ]] || cmd="cargo build -p engine --bin mundus-engine"
        [[ $dry -eq 1 || $build -eq 1 ]] || stop_installed_engine
        ;;
    manager)
        cd manager-gpui
        watch=(--watch src --watch assets --watch Cargo.toml --watch Cargo.lock --watch build.rs)
        cmd="cargo run --bin manager-gpui"
        [[ $build -eq 0 ]] || cmd="cargo build --bin manager-gpui"
        if [[ $local_imago -eq 1 ]]; then
            imago="$(cd ../../imago && { pwd -W 2>/dev/null || pwd; })"
            mkdir -p .cargo
            printf '# Local development override, generated by dev-watch.sh\n[patch."https://github.com/makekosmos/imago.git"]\nimago-gpui = { path = "%s/crates/imago-gpui" }\nmundus-gpui-kit = { path = "%s/crates/mundus-gpui-kit" }\n' \
                "$imago" "$imago" > .cargo/imago-local.toml
            watch+=(--watch "$imago/crates/imago-gpui/src" --watch "$imago/crates/imago-gpui/assets"
                --watch "$imago/crates/imago-gpui/Cargo.toml" --watch "$imago/crates/mundus-gpui-kit/src"
                --watch "$imago/crates/mundus-gpui-kit/Cargo.toml")
            cmd="cargo --config .cargo/imago-local.toml ${cmd#cargo }"
        fi
        ;;
    *) usage ;;
esac

if [[ $build -eq 1 ]]; then final=($cmd); else final=(cargo watch "${watch[@]}" -s "$cmd"); fi
if [[ $dry -eq 1 ]]; then printf '(cd %q) ' "$PWD"; printf '%q ' "${final[@]}"; echo; exit 0; fi
exec "${final[@]}"
