#![allow(clippy::unwrap_used)]
//! KOS-297 contract test: every payload agenda-gpui's write path produces must
//! pass the exact validation the Engine runs on `upsert_object`
//! (`canonical_types::ingress::prepare_object` → `validate_canonical`).
//!
//! The fixtures under `tests/fixtures/agenda/` are generated by the
//! `engine_payload_fixtures_match_write_output` test in agenda-gpui
//! (`AGENDA_EMIT_FIXTURES=1 cargo test engine_payload_fixtures`, then copy
//! `fixtures/engine/*.json` here). A schema change in ark-core that rejects an
//! Agenda payload fails here; a write-path change in Agenda fails its own
//! fixture drift test there.

use ark_core::canonical_types::ingress::prepare_object;
use ark_core::db::init_schema;
use ark_core::types::ArkObjectWrite;
use rusqlite::Connection;
use std::path::PathBuf;

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/agenda")
}

#[test]
fn agenda_write_payloads_pass_engine_validation() {
    let conn = Connection::open_in_memory().unwrap();
    init_schema(&conn).unwrap();

    let mut names: Vec<String> = std::fs::read_dir(fixture_dir())
        .unwrap()
        .filter_map(|entry| {
            let name = entry.unwrap().file_name().into_string().unwrap();
            name.ends_with(".json").then_some(name)
        })
        .collect();
    names.sort();
    // The scenario set is pinned: a fixture silently dropped from the
    // directory would shrink the contract without failing anything.
    let expected = [
        "task-canceled",
        "task-date",
        "task-deadline",
        "task-inbox",
        "task-note",
        "task-project",
        "task-recurrence",
        "task-significance-unset",
        "task-completed",
    ];
    let mut expected_names: Vec<String> = expected
        .iter()
        .flat_map(|base| [format!("{base}.json"), format!("{base}-edited.json")])
        .collect();
    expected_names.sort();
    assert_eq!(names, expected_names, "fixture set drifted");

    for name in names {
        let raw: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(fixture_dir().join(&name)).unwrap())
                .unwrap();
        let write: ArkObjectWrite = serde_json::from_value(raw)
            .unwrap_or_else(|e| panic!("{name}: not an engine object envelope: {e}"));
        prepare_object(&conn, write)
            .unwrap_or_else(|e| panic!("{name}: Engine ingress rejected Agenda payload: {e}"));
    }
}
