pub fn fixtures() -> Vec<TodoItem> {
    [
        Spec {
            id: "inbox-1",
            status: "todo",
            scheduled: None,
            completed: None,
            canceled: None,
            today: false,
            someday: false,
            trashed: false,
            sort_order: 1,
            created_at: "2026-05-13T10:00:00.000Z",
            project: None,
        },
        Spec {
            id: "inbox-2",
            status: "todo",
            scheduled: None,
            completed: None,
            canceled: None,
            today: false,
            someday: false,
            trashed: false,
            sort_order: 2,
            created_at: "2026-05-14T10:00:00.000Z",
            project: None,
        },
        Spec {
            id: "today-flag",
            status: "todo",
            scheduled: None,
            completed: None,
            canceled: None,
            today: true,
            someday: false,
            trashed: false,
            sort_order: 10,
            created_at: "2026-05-15T10:00:00.000Z",
            project: None,
        },
        Spec {
            id: "today-scheduled",
            status: "todo",
            scheduled: Some(TODAY_ISO),
            completed: None,
            canceled: None,
            today: false,
            someday: false,
            trashed: false,
            sort_order: 5,
            created_at: "2026-05-15T10:00:00.000Z",
            project: None,
        },
        Spec {
            id: "upcoming-1",
            status: "todo",
            scheduled: Some("2026-06-01"),
            completed: None,
            canceled: None,
            today: false,
            someday: false,
            trashed: false,
            sort_order: 100,
            created_at: "2026-05-10T00:00:00.000Z",
            project: None,
        },
        Spec {
            id: "upcoming-2",
            status: "todo",
            scheduled: Some("2026-05-20"),
            completed: None,
            canceled: None,
            today: false,
            someday: false,
            trashed: false,
            sort_order: 99,
            created_at: "2026-05-11T00:00:00.000Z",
            project: None,
        },
        Spec {
            id: "someday-1",
            status: "todo",
            scheduled: None,
            completed: None,
            canceled: None,
            today: false,
            someday: true,
            trashed: false,
            sort_order: 50,
            created_at: "2026-05-15T10:00:00.000Z",
            project: None,
        },
        Spec {
            id: "someday-2",
            status: "todo",
            scheduled: None,
            completed: None,
            canceled: None,
            today: false,
            someday: true,
            trashed: false,
            sort_order: 51,
            created_at: "2026-05-15T10:00:00.000Z",
            project: None,
        },
        Spec {
            id: "proj-task",
            status: "todo",
            scheduled: Some("2026-05-20"),
            completed: None,
            canceled: None,
            today: false,
            someday: false,
            trashed: false,
            sort_order: 7,
            created_at: "2026-05-15T10:00:00.000Z",
            project: Some("proj-1"),
        },
        Spec {
            id: "completed-1",
            status: "done",
            scheduled: None,
            completed: Some("2026-05-14T12:00:00.000Z"),
            canceled: None,
            today: false,
            someday: false,
            trashed: false,
            sort_order: 0,
            created_at: "2026-05-15T10:00:00.000Z",
            project: None,
        },
        Spec {
            id: "completed-2",
            status: "done",
            scheduled: None,
            completed: Some("2026-05-15T08:00:00.000Z"),
            canceled: None,
            today: false,
            someday: false,
            trashed: false,
            sort_order: 0,
            created_at: "2026-05-15T10:00:00.000Z",
            project: None,
        },
        Spec {
            id: "cancelled-1",
            status: "canceled",
            scheduled: None,
            completed: None,
            canceled: Some("2026-05-13T15:00:00.000Z"),
            today: false,
            someday: false,
            trashed: false,
            sort_order: 0,
            created_at: "2026-05-15T10:00:00.000Z",
            project: None,
        },
        Spec {
            id: "trash-1",
            status: "todo",
            scheduled: None,
            completed: None,
            canceled: None,
            today: false,
            someday: false,
            trashed: true,
            sort_order: 0,
            created_at: "2026-05-12T10:00:00.000Z",
            project: None,
        },
        Spec {
            id: "trash-2",
            status: "todo",
            scheduled: None,
            completed: None,
            canceled: None,
            today: false,
            someday: false,
            trashed: true,
            sort_order: 0,
            created_at: "2026-05-15T11:00:00.000Z",
            project: None,
        },
        Spec {
            id: "scheduled-today-completed",
            status: "done",
            scheduled: Some(TODAY_ISO),
            completed: Some("2026-05-15T10:00:00.000Z"),
            canceled: None,
            today: false,
            someday: false,
            trashed: false,
            sort_order: 0,
            created_at: "2026-05-15T10:00:00.000Z",
            project: None,
        },
        Spec {
            id: "trashed-completed",
            status: "done",
            scheduled: None,
            completed: Some("2026-05-14T10:00:00.000Z"),
            canceled: None,
            today: false,
            someday: false,
            trashed: true,
            sort_order: 0,
            created_at: "2026-05-15T10:00:00.000Z",
            project: None,
        },
    ]
    .into_iter()
    .map(|spec| {
        let (object, links) = canonical(&spec);
        project_task_to_delphi(&object, &links).expect("canonical fixture must project")
    })
    .collect()
}

