import {
  BookOpen,
  Bug,
  Clipboard,
  Gamepad2,
  Info,
  KeyRound,
  ListTodo,
  Mic,
  MicVocal,
  Puzzle,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Timer,
  RefreshCw,
} from "@lucide/vue";
import kosmosIconPng from "../../../build/icon.png";
import { CLIPBOARD_HISTORY_ENABLED } from "@shared/ipc-types";

import type { SettingsNavigationItem } from "./navigation";

export const settingsNavigationItems: SettingsNavigationItem[] = [
  {
    tab: "general",
    label: "Общие",
    group: "main",
    layout: "basic",
    icon: Settings,
    keywords: [
      "общие",
      "настройки",
      "глобальный хоткей",
      "launcher",
      "автозапуск",
      "windows",
      "трей",
      "tray",
    ],
  },
  {
    tab: "security",
    label: "Безопасность",
    group: "main",
    layout: "basic",
    icon: ShieldCheck,
    description: "Сеть для AI-провайдеров и доступ к данным.",
    keywords: ["безопасность", "сеть", "dns", "doh", "ai", "groq", "прокси", "блокировки", "рф"],
  },
  {
    tab: "sync",
    label: "Синхронизация",
    group: "main",
    layout: "basic",
    icon: RefreshCw,
    description: "Устройства, код подключения и состояние синхронизации.",
    keywords: [
      "синхронизация",
      "sync",
      "устройства",
      "ноды",
      "nodes",
      "код",
      "подключение",
      "pairing",
      "iroh",
    ],
  },
  {
    tab: "debug",
    label: "Дебаг",
    group: "main",
    layout: "basic",
    icon: Bug,
    keywords: [
      "дебаг",
      "debug",
      "developer mode",
      "режим разработчика",
      "backend",
      "lock файл",
      "отчеты об ошибках",
      "bug report",
      "логи",
      "crash",
      "позиция в лаунчере",
    ],
  },
  {
    tab: "about",
    label: "О приложении",
    group: "main",
    layout: "basic",
    icon: Info,
    introImage: kosmosIconPng,
    description: "Kepler shell и обновления приложения.",
    keywords: ["about", "о приложении", "версия", "kepler", "kosmos", "обновления", "update"],
  },
  {
    tab: "file-search",
    label: "Поиск файлов",
    group: "advanced",
    layout: "advanced",
    icon: Search,
    iconGradient: { from: "#94A3B8", to: "#334155" },
    description: "Индексация локальных файлов и исключения шумных папок.",
    keywords: [
      "поиск файлов",
      "file search",
      "индексация файлов",
      "шумные папки",
      "node_modules",
      ".git",
      "переиндексация",
      "локальные диски",
    ],
  },
  {
    tab: "ai",
    label: "AI",
    group: "advanced",
    layout: "advanced",
    icon: MicVocal,
    iconGradient: { from: "#F472B6", to: "#BE185D" },
    description: "Модели и API-ключи для AI.",
    keywords: [
      "ai",
      "искусственный интеллект",
      "модель",
      "модели",
      "локальная модель",
      "локально",
      "groq",
      "whisper",
      "speech to text",
      "stt",
    ],
  },
  {
    tab: "secrets",
    label: "Секреты",
    group: "advanced",
    layout: "advanced",
    icon: KeyRound,
    description: "API-ключи, токены и подключения сервисов для всех приложений Kosmos.",
    keywords: ["секреты", "api", "api ключ", "ключ", "token", "groq", "rawg", "credentials"],
  },
  {
    tab: "extensions",
    label: "Расширения",
    group: "advanced",
    layout: "advanced",
    icon: Puzzle,
    iconGradient: { from: "#A78BFA", to: "#5B21B6" },
    description: "Установленные расширения, каталог и управление приложениями.",
    keywords: [
      "расширения",
      "каталог",
      "marketplace",
      "установленные",
      "список приложений",
      "eden",
      "delphi",
      "arrancador",
      "focus",
    ],
  },
  {
    tab: "dictation",
    label: "Диктация",
    group: "advanced",
    layout: "advanced",
    icon: Mic,
    iconGradient: { from: "#F472B6", to: "#7C2D12" },
    description: "Голосовой ввод локально или через подключённый провайдер.",
    keywords: [
      "диктация",
      "stt",
      "голос",
      "whisper",
      "groq",
      "распознавание речи",
      "транскрипция",
      "voice",
    ],
  },
  // Буфер обмена заморожен — вкладка скрыта (CLIPBOARD_HISTORY_ENABLED).
  ...(CLIPBOARD_HISTORY_ENABLED
    ? [
        {
          tab: "clipboard",
          label: "Буфер обмена",
          group: "advanced",
          layout: "advanced",
          icon: Clipboard,
          iconGradient: {
            from: "var(--accent)",
            to: "color-mix(in srgb, var(--accent) 58%, var(--background))",
          },
          description: "История скопированных данных, срок хранения и лимит места.",
          keywords: [
            "буфер обмена",
            "clipboard",
            "история буфера",
            "копирование",
            "retention",
            "пины",
            "срок хранения",
            "лимит места",
          ],
        } satisfies SettingsNavigationItem,
      ]
    : []),
  {
    tab: "focus",
    label: "Фокус",
    group: "advanced",
    layout: "advanced",
    icon: Shield,
    iconGradient: { from: "#60A5FA", to: "#1D4ED8" },
    description: "Блокировка отвлечений и системный демон фокус-режима.",
    keywords: [
      "фокус",
      "блокировка",
      "системный демон",
      "focus service",
      "активная блокировка",
      "blocklist",
      "домены",
      "сайты",
      "hosts",
      "pomodoro",
    ],
  },
  {
    tab: "tasks",
    label: "Задачи",
    group: "advanced",
    layout: "advanced",
    icon: ListTodo,
    iconGradient: { from: "#2DD4BF", to: "#0F766E" },
    description: "Delphi: задачи, списки и рабочие действия.",
    keywords: ["задачи", "delphi", "todo", "task", "списки", "дела"],
  },
  {
    tab: "notes",
    label: "Заметки",
    group: "advanced",
    layout: "advanced",
    icon: BookOpen,
    iconGradient: { from: "#7C5CFF", to: "#3A237D" },
    description: "Eden: заметки, дневник и быстрый доступ к текстам.",
    keywords: ["заметки", "eden", "дневник", "note", "journal", "тексты"],
  },
  {
    tab: "time-tracker",
    label: "Фокус-таймер",
    group: "advanced",
    layout: "advanced",
    icon: Timer,
    iconGradient: { from: "#F59E0B", to: "#92400E" },
    sidebarImage: kosmosIconPng,
    introImage: kosmosIconPng,
    description: "Shell-owned фокус-сессии, задача и таймер.",
    keywords: [
      "фокус-таймер",
      "трекер времени",
      "time tracker",
      "pomodoro",
      "таймер",
      "focus",
      "трекать активные приложения",
      "usage tracker",
    ],
  },
  {
    tab: "games",
    label: "Игры",
    group: "advanced",
    layout: "advanced",
    icon: Gamepad2,
    iconGradient: { from: "#F472B6", to: "#9D174D" },
    description: "Arrancador: библиотека игр и связанные настройки.",
    keywords: ["игры", "arrancador", "games", "game library", "библиотека игр"],
  },
];
