export { ArkClient } from './ark-client.js'
export {
  buildPersonalSelectedSpace,
  buildSharedSelectedSpaceFromCode,
  derivePersonalSpaceCodeFromVaultPath,
  deriveSpaceIdFromCode,
  getArkDbPathForSelectedSpace,
  getKosmosDataDir,
  getSharedSelectedSpacePath,
  readSharedSelectedSpace,
  writeSharedSelectedSpace,
} from './selected-space.js'
export type { SharedSelectedSpace } from './selected-space.js'
export {
  KEPLER_LOCK_FILENAME,
  ensureKeplerRunning,
  isPidAlive,
  readLockIfAlive,
  resolveKeplerExe,
  resolveLockPath,
} from './ensure-kepler.js'
export type {
  EnsureKeplerOptions,
  KeplerLockInfo,
  KeplerProtocolVersion,
  KeplerState,
} from './ensure-kepler.js'
export type {
  ArkClientOptions,
  ArkCommandsApi,
  ArkDailyTrendPoint,
  ArkHourlyHeatmapCell,
  ArkKvApi,
  ArkLinksApi,
  ArkObjectLinkRecord,
  ArkObjectRecord,
  ArkObjectsApi,
  ArkObjectTypeRecord,
  ArkObjectTypesApi,
  ArkRecentSessionEntry,
  ArkSearchResult,
  ArkTopAppEntry,
  ArkUsageAnalyticsOptions,
  ArkUsageAnalyticsSnapshot,
  ArkTrackedAppRecord,
  ArkUsageApi,
  ArkUsageEntityApi,
  ArkUsageEventRecord,
  ArkUsageGameDailyTotal,
  ArkUsageGamePlaytimeAggregate,
  ArkUsageGamePlaytimeBinding,
  ArkUsageGamePlaytimeSummary,
  ArkUsageGamePlaytimeSummaryOptions,
  ArkUsageGameRangeTotal,
  ArkUsageProcessCandidate,
  ArkUsageSessionRecord,
  ArkUsageSnapshot,
  ArkUsageSummary,
  CommandInvokedCallback,
  CommandInvokedEvent,
  CommandManifest,
  CommandsChangedCallback,
  ConnectedPeer,
  PeerConnectedCallback,
  PeerDisconnectedCallback,
  EntityChangedCallback,
  JsonValue,
} from './ark-client.js'
