export { ArkClient } from "./ark-client.js";
// Generated bindings из Rust ark-core (Phase 5 bug-detection).
// См. packages/ark/src/generated/index.ts.
export type { ArkObject, ObjectType, ObjectLink } from "./generated/index.js";
export {
  KEPLER_LOCK_FILENAME,
  ensureKeplerRunning,
  isPidAlive,
  readLockIfAlive,
  resolveKeplerExe,
  resolveLockPath,
} from "./ensure-kepler.js";
export type {
  EnsureKeplerOptions,
  KeplerLockInfo,
  KeplerProtocolVersion,
  KeplerState,
} from "./ensure-kepler.js";
export type {
  ArkClientOptions,
  ArkCommandsApi,
  ArkDailyTrendPoint,
  ArkHourlyHeatmapCell,
  ArkKvApi,
  ArkLinksApi,
  ArkObjectLinkRecord,
  ArkObjectRecord,
  ArkObjectsApi,
  ArkObjectTypeRecord,
  ArkObjectTypesApi,
  ArkRecentSessionEntry,
  ArkSearchResult,
  ArkTopAppEntry,
  ArkUsageAnalyticsOptions,
  ArkUsageAnalyticsSnapshot,
  ArkTrackedAppRecord,
  ArkUsageApi,
  ArkUsageEntityApi,
  ArkUsageEventRecord,
  ArkUsageGameDailyTotal,
  ArkUsageGamePlaytimeAggregate,
  ArkUsageGamePlaytimeBinding,
  ArkUsageGamePlaytimeSummary,
  ArkUsageGamePlaytimeSummaryOptions,
  ArkUsageGameRangeTotal,
  ArkUsageProcessCandidate,
  ArkUsageSessionRecord,
  ArkUsageSnapshot,
  ArkUsageSummary,
  CommandInvokedCallback,
  CommandInvokedEvent,
  CommandManifest,
  CommandsChangedCallback,
  ConnectedPeer,
  PeerConnectedCallback,
  PeerDisconnectedCallback,
  EntityChangedCallback,
  JsonValue,
} from "./ark-client.js";
