export { ArkClient } from './ark-client.js'
export {
  buildPersonalSelectedSpace,
  buildSharedSelectedSpaceFromCode,
  derivePersonalSpaceCodeFromVaultPath,
  deriveSpaceIdFromCode,
  getArkDbPathForSelectedSpace,
  getKeplerDataDir,
  getSharedSelectedSpacePath,
  readSharedSelectedSpace,
  writeSharedSelectedSpace,
} from './selected-space.js'
export type { SharedSelectedSpace } from './selected-space.js'
export {
  KOSMOS_LOCK_FILENAME,
  ensureKosmosRunning,
  isPidAlive,
  readLockIfAlive,
  resolveKosmosExe,
  resolveLockPath,
} from './ensure-kosmos.js'
export type {
  EnsureKosmosOptions,
  KosmosLockInfo,
  KosmosProtocolVersion,
  KosmosState,
} from './ensure-kosmos.js'
export type {
  ArkClientOptions,
  ArkDailyTrendPoint,
  ArkHourlyHeatmapCell,
  ArkKvApi,
  ArkLinksApi,
  ArkObjectLinkRecord,
  ArkObjectRecord,
  ArkObjectsApi,
  ArkObjectTypeRecord,
  ArkObjectTypesApi,
  ArkRecentSessionEntry,
  ArkSearchResult,
  ArkTopAppEntry,
  ArkUsageAnalyticsOptions,
  ArkUsageAnalyticsSnapshot,
  ArkTrackedAppRecord,
  ArkUsageApi,
  ArkUsageEntityApi,
  ArkUsageEventRecord,
  ArkUsageGameDailyTotal,
  ArkUsageGamePlaytimeAggregate,
  ArkUsageGamePlaytimeBinding,
  ArkUsageGamePlaytimeSummary,
  ArkUsageGamePlaytimeSummaryOptions,
  ArkUsageGameRangeTotal,
  ArkUsageProcessCandidate,
  ArkUsageSessionRecord,
  ArkUsageSnapshot,
  ArkUsageSummary,
  ConnectedPeer,
  PeerConnectedCallback,
  PeerDisconnectedCallback,
  EntityChangedCallback,
  JsonValue,
} from './ark-client.js'
